// Core set — "Emberwood" (EMB). Keywords in play:
//   ambush    — can attack the turn it's played
//   guardian  — enemies must attack this unit first
//   ward      — can't be targeted by enemy spells
//   frenzy    — attacks twice per turn
//   lifesteal — attacking restores that much Hearth
//   piercing  — excess damage from kills carries to the enemy Hearth
//
// storiedKeyword: the keyword this card gains at Storied renown (Chronicle L3).
import { registerCards } from '../../engine/cards.js';

registerCards([
  // ---- creatures: boars & beasts ----
  { id: 'young_boar', set: 'core', rarity: 'common', type: 'creature', cost: 1, atk: 2, hp: 1, storiedKeyword: 'ambush',
    name: 'Young Boar', text: '', flavor: 'All tusk, no plan.' },
  { id: 'wild_boar', set: 'core', rarity: 'common', type: 'creature', cost: 2, atk: 2, hp: 3, storiedKeyword: 'piercing',
    name: 'Wild Boar', text: '', flavor: 'Turnip enthusiast.' },
  { id: 'tusker', set: 'core', rarity: 'common', type: 'creature', cost: 3, atk: 4, hp: 2, keywords: ['ambush'], storiedKeyword: 'frenzy',
    name: 'Charging Tusker', text: '', flavor: 'Never saw a fence it respected.' },
  { id: 'boar_matron', set: 'core', rarity: 'uncommon', type: 'creature', cost: 4, atk: 3, hp: 5,
    triggers: { onDeath: [{ effect: 'summon', token: 'young_boar', count: 2 }] },
    name: 'Boar Matron', text: 'When she dies, summon two Young Boars.', flavor: 'The herd provides.' },
  { id: 'darkwood_wolf', set: 'core', rarity: 'common', type: 'creature', cost: 3, atk: 3, hp: 3, storiedKeyword: 'lifesteal',
    triggers: { onAttack: [{ effect: 'buff', target: 'self', atk: 1 }] },
    name: 'Darkwood Wolf', text: 'Whenever this attacks, it gains +1 attack.', flavor: 'The pack remembers.' },
  { id: 'pack_alpha', set: 'core', rarity: 'rare', type: 'creature', cost: 5, atk: 4, hp: 4,
    triggers: { onPlay: [{ effect: 'buff', target: 'allAllies', atk: 1, hp: 0 }] },
    name: 'Pack Alpha', text: 'When played, your other creatures get +1 attack.', flavor: 'First among tusks and teeth.' },
  { id: 'gruk', set: 'core', rarity: 'rare', type: 'creature', cost: 7, atk: 7, hp: 7, keywords: ['guardian'],
    triggers: { onPlay: [{ effect: 'damage', target: 'allEnemies', amount: 2 }] },
    name: 'Gruk, the Boar King', text: 'When played, deal 2 damage to all enemy creatures.', flavor: 'The hollow of bones is his throne room.' },

  // ---- creatures: villagers & wardens ----
  { id: 'militia_recruit', set: 'core', rarity: 'common', type: 'creature', cost: 1, atk: 1, hp: 2, keywords: ['guardian'],
    name: 'Militia Recruit', text: '', flavor: 'Standing exactly where he was told.' },
  { id: 'village_warden', set: 'core', rarity: 'common', type: 'creature', cost: 3, atk: 2, hp: 4, keywords: ['guardian'],
    name: 'Village Warden', text: '', flavor: 'Keep to the roads after dark.' },
  { id: 'quartermaster', set: 'core', rarity: 'uncommon', type: 'creature', cost: 2, atk: 1, hp: 3,
    triggers: { onPlay: [{ effect: 'draw', amount: 1 }] },
    name: 'Quartermaster', text: 'When played, draw a card.', flavor: 'Everything in its place, twice counted.' },
  { id: 'hearth_keeper', set: 'core', rarity: 'uncommon', type: 'creature', cost: 3, atk: 2, hp: 3,
    triggers: { startOfTurn: [{ effect: 'heal', target: 'ownHearth', amount: 1 }] },
    name: 'Hearth Keeper', text: 'At the start of your turn, restore 1 to your Hearth.', flavor: 'The fire never dies on her watch.' },
  { id: 'beacon_mage', set: 'core', rarity: 'rare', type: 'creature', cost: 4, atk: 3, hp: 3, keywords: ['ward'],
    triggers: { onPlay: [{ effect: 'damage', target: 'chosen', amount: 2 }] },
    needsTarget: 'enemyUnit',
    name: 'Beacon Mage', text: 'When played, deal 2 damage to an enemy creature.', flavor: 'Light that answers back.' },

  // ---- creatures: bandits ----
  { id: 'red_sash_cutpurse', set: 'core', rarity: 'common', type: 'creature', cost: 2, atk: 3, hp: 1, keywords: ['ambush'],
    name: 'Red-Sash Cutpurse', text: '', flavor: 'Taxes travelers with knives.' },
  { id: 'red_sash_duelist', set: 'core', rarity: 'uncommon', type: 'creature', cost: 4, atk: 3, hp: 3, keywords: ['frenzy'],
    name: 'Red-Sash Duelist', text: '', flavor: 'No manners. Twice.' },
  { id: 'camp_torcher', set: 'core', rarity: 'uncommon', type: 'creature', cost: 3, atk: 2, hp: 2,
    triggers: { onDeath: [{ effect: 'damage', target: 'randomEnemy', amount: 2 }] },
    name: 'Camp Torcher', text: 'When this dies, deal 2 damage to a random enemy.', flavor: 'Goes out with a bang.' },

  // ---- spells ----
  { id: 'ember_bolt', set: 'core', rarity: 'common', type: 'spell', cost: 1,
    triggers: { onPlay: [{ effect: 'damage', target: 'chosen', amount: 2 }] }, needsTarget: 'any',
    name: 'Ember Bolt', text: 'Deal 2 damage to anything.', flavor: 'The forest\'s oldest argument.' },
  { id: 'kindled_fury', set: 'core', rarity: 'common', type: 'spell', cost: 2,
    triggers: { onPlay: [{ effect: 'buff', target: 'chosen', atk: 2, hp: 1 }] }, needsTarget: 'anyUnit',
    name: 'Kindled Fury', text: 'Give a creature +2/+1.', flavor: 'Feed the spark.' },
  { id: 'wolf_howl', set: 'core', rarity: 'uncommon', type: 'spell', cost: 3,
    triggers: { onPlay: [{ effect: 'summon', token: 'darkwood_wolf', count: 1 }, { effect: 'draw', amount: 1 }] },
    name: 'Wolf Howl', text: 'Summon a Darkwood Wolf and draw a card.', flavor: 'The dark answers.' },
  { id: 'controlled_burn', set: 'core', rarity: 'rare', type: 'spell', cost: 5,
    triggers: { onPlay: [{ effect: 'damage', target: 'allEnemies', amount: 3 }] },
    name: 'Controlled Burn', text: 'Deal 3 damage to all enemy creatures.', flavor: 'Mostly controlled.' },
  { id: 'hearth_meal', set: 'core', rarity: 'common', type: 'spell', cost: 2,
    triggers: { onPlay: [{ effect: 'heal', target: 'ownHearth', amount: 5 }] },
    name: 'Hearth Meal', text: 'Restore 5 to your Hearth.', flavor: 'Warm bread, warmer hearth.' },
  { id: 'sudden_spark', set: 'core', rarity: 'uncommon', type: 'spell', cost: 0,
    triggers: { onPlay: [{ effect: 'emberGain', amount: 2 }] },
    name: 'Sudden Spark', text: 'Gain 2 Ember this turn.', flavor: 'Now. NOW.' },

  // ---- creatures: new blood ----
  { id: 'nightstalker', set: 'core', rarity: 'rare', type: 'creature', cost: 4, atk: 4, hp: 2, keywords: ['ambush', 'lifesteal'],
    name: 'Darkwood Nightstalker', text: '', flavor: 'The dark under the trees, on the hunt.' },
  { id: 'ironhide_boar', set: 'core', rarity: 'uncommon', type: 'creature', cost: 5, atk: 4, hp: 6, keywords: ['piercing'],
    name: 'Ironhide Boar', text: '', flavor: 'Fences, walls, militias — all the same to him.' },
  { id: 'emberwood_colossus', set: 'core', rarity: 'rare', type: 'creature', cost: 6, atk: 6, hp: 6, keywords: ['guardian'], storiedKeyword: 'piercing',
    name: 'Emberwood Colossus', text: '', flavor: 'The forest, when it stands up.' },

  // ---- relics (attach to one of your creatures) ----
  { id: 'tusk_talisman', set: 'core', rarity: 'common', type: 'relic', cost: 1,
    triggers: { onPlay: [{ effect: 'buff', target: 'chosen', atk: 2, hp: 0 }] }, needsTarget: 'ownUnit',
    name: 'Tusk Talisman', text: 'Attach: your creature gets +2 attack.', flavor: 'Worn tusk, sharp memory.' },
  { id: 'wardenplate', set: 'core', rarity: 'uncommon', type: 'relic', cost: 2,
    triggers: { onPlay: [{ effect: 'buff', target: 'chosen', atk: 0, hp: 3 }, { effect: 'grantKeyword', target: 'chosen', keyword: 'guardian' }] }, needsTarget: 'ownUnit',
    name: 'Wardenplate', text: 'Attach: your creature gets +3 health and Guardian.', flavor: 'Issued, dented, trusted.' },
  { id: 'ember_fang', set: 'core', rarity: 'rare', type: 'relic', cost: 3,
    triggers: { onPlay: [{ effect: 'buff', target: 'chosen', atk: 2, hp: 1 }, { effect: 'grantKeyword', target: 'chosen', keyword: 'lifesteal' }] }, needsTarget: 'ownUnit',
    name: 'Ember Fang', text: 'Attach: your creature gets +2/+1 and Lifesteal.', flavor: 'Still warm.' },

  // ---- new spells ----
  { id: 'second_wind', set: 'core', rarity: 'uncommon', type: 'spell', cost: 2,
    triggers: { onPlay: [{ effect: 'buff', target: 'chosen', atk: 0, hp: 2 }, { effect: 'refresh', target: 'chosen' }] }, needsTarget: 'ownUnit',
    name: 'Second Wind', text: 'Your creature gets +0/+2 and may attack again.', flavor: 'Get up.' },
  { id: 'ashen_rite', set: 'core', rarity: 'uncommon', type: 'spell', cost: 3,
    triggers: { onPlay: [{ effect: 'damage', target: 'chosen', amount: 4 }] }, needsTarget: 'enemyUnit',
    name: 'Ashen Rite', text: 'Deal 4 damage to an enemy creature.', flavor: 'Ash remembers what fire forgets.' },

  // ---- reactions (set face-down, max 2; auto-fire on the named enemy event) ----
  { id: 'hidden_snare', set: 'core', rarity: 'common', type: 'reaction', cost: 1,
    reaction: { on: 'enemyAttack', effects: [{ effect: 'damage', target: 'trigger', amount: 2 }] },
    name: 'Hidden Snare', text: 'Reaction: when an enemy creature attacks, deal 2 damage to it.', flavor: 'The path was too quiet.' },
  { id: 'boar_pit', set: 'core', rarity: 'uncommon', type: 'reaction', cost: 2,
    reaction: { on: 'enemyAttack', effects: [{ effect: 'damage', target: 'trigger', amount: 4 }] },
    name: 'Boar Pit', text: 'Reaction: when an enemy creature attacks, deal 4 damage to it.', flavor: 'Dug for boars. Works on everything.' },
  { id: 'alarm_bell', set: 'core', rarity: 'common', type: 'reaction', cost: 2,
    reaction: { on: 'enemyAttack', effects: [{ effect: 'summon', token: 'militia_recruit', count: 1 }] },
    name: 'Alarm Bell', text: 'Reaction: when an enemy creature attacks, summon a Militia Recruit.', flavor: 'The village answers its own.' },
  { id: 'warding_bell', set: 'core', rarity: 'uncommon', type: 'reaction', cost: 2,
    reaction: { on: 'enemyCreature', effects: [{ effect: 'damage', target: 'trigger', amount: 2 }] },
    name: 'Warding Bell', text: 'Reaction: when your opponent plays a creature, deal 2 damage to it.', flavor: 'Rung once for wolves, twice for worse.' },
  { id: 'counterspark', set: 'core', rarity: 'rare', type: 'reaction', cost: 3,
    reaction: { on: 'enemySpell', effects: [{ effect: 'counter' }] },
    name: 'Counterspark', text: "Reaction: when your opponent plays a spell, its effects don't happen.", flavor: 'Fire, meet firebreak.' },

  // ---- kindle-matters (the signature resource becomes a build-around) ----
  { id: 'ash_sprite', set: 'core', rarity: 'common', type: 'creature', cost: 2, atk: 2, hp: 2, storiedKeyword: 'ward',
    triggers: { onKindle: [{ effect: 'buff', target: 'self', atk: 1, hp: 1 }] },
    name: 'Ash Sprite', text: 'When you kindle, this gains +1/+1.', flavor: 'Born in the burnt page of a story.' },
  { id: 'flame_tender', set: 'core', rarity: 'uncommon', type: 'creature', cost: 3, atk: 2, hp: 4, storiedKeyword: 'guardian',
    triggers: { onKindle: [{ effect: 'heal', target: 'ownHearth', amount: 2 }] },
    name: 'Flame Tender', text: 'When you kindle, restore 2 to your Hearth.', flavor: 'Every offering earns a warmth back.' },
  { id: 'pyre_keeper', set: 'core', rarity: 'rare', type: 'creature', cost: 4, atk: 3, hp: 4, storiedKeyword: 'ward',
    triggers: { onKindle: [{ effect: 'damage', target: 'randomEnemy', amount: 1 }] },
    name: 'Pyre Keeper', text: 'When you kindle, deal 1 damage to a random enemy.', flavor: 'What burns for her, burns for you.' },
  { id: 'stoke_the_flames', set: 'core', rarity: 'uncommon', type: 'spell', cost: 1,
    triggers: { onPlay: [{ effect: 'resetKindle' }, { effect: 'draw', amount: 1 }] },
    name: 'Stoke the Flames', text: 'You may kindle again this turn. Draw a card.', flavor: 'The fire is never finished eating.' },

  // ---- graveyard-matters (the ashes remember) ----
  { id: 'ashen_shambler', set: 'core', rarity: 'uncommon', type: 'creature', cost: 3, atk: 2, hp: 2, storiedKeyword: 'lifesteal',
    triggers: { onPlay: [{ effect: 'graveBuff', filter: 'creature', atk: 1, hp: 1, cap: 4 }] },
    name: 'Ashen Shambler', text: 'When played, gains +1/+1 for each creature in your graveyard (up to +4/+4).', flavor: 'It walks the way grief does.' },
  { id: 'last_rites', set: 'core', rarity: 'uncommon', type: 'spell', cost: 2,
    triggers: { onPlay: [{ effect: 'exhume', amount: 1 }] },
    name: 'Last Rites', text: 'Return a random creature from your graveyard to your hand.', flavor: 'Not yet, the words say. Not yet.' },
  { id: 'second_harvest', set: 'core', rarity: 'rare', type: 'spell', cost: 4,
    triggers: { onPlay: [{ effect: 'exhume', amount: 2 }, { effect: 'heal', target: 'ownHearth', amount: 2 }] },
    name: 'Second Harvest', text: 'Return two random creatures from your graveyard to your hand. Restore 2 Hearth.', flavor: 'The forest wastes nothing.' },

  // ---- new blood for existing families ----
  { id: 'forest_sow', set: 'core', rarity: 'common', type: 'creature', cost: 2, atk: 1, hp: 4, keywords: ['guardian'], storiedKeyword: 'ward',
    name: 'Forest Sow', text: '', flavor: 'Do not stand between her and the piglets.' },
  { id: 'dire_wolf', set: 'core', rarity: 'uncommon', type: 'creature', cost: 4, atk: 4, hp: 3, storiedKeyword: 'frenzy',
    name: 'Dire Wolf', text: '', flavor: 'The howl you hoped was the wind.' },
  { id: 'red_sash_ambusher', set: 'core', rarity: 'common', type: 'creature', cost: 3, atk: 3, hp: 2, keywords: ['ambush'], storiedKeyword: 'piercing',
    name: 'Red-Sash Ambusher', text: '', flavor: 'The toll is whatever you carry.' },
  { id: 'warden_captain', set: 'core', rarity: 'rare', type: 'creature', cost: 5, atk: 4, hp: 5, keywords: ['guardian'], storiedKeyword: 'ward',
    triggers: { onPlay: [{ effect: 'buff', target: 'allAllies', atk: 0, hp: 1 }] },
    name: 'Warden Captain', text: 'When played, your other creatures get +1 health.', flavor: 'Hold the line. The line is us.' },
  { id: 'thicket_beast', set: 'core', rarity: 'common', type: 'creature', cost: 4, atk: 3, hp: 5, storiedKeyword: 'guardian',
    name: 'Thicket Beast', text: '', flavor: 'Mostly moss. Partly teeth.' },

  // ---- enchantments (face-up, persistent, player-wide — see engine.js) ----
  { id: 'herd_instinct', set: 'core', rarity: 'uncommon', type: 'enchantment', cost: 3,
    triggers: {
      onPlay: [{ effect: 'buff', target: 'allAllies', atk: 1, hp: 0 }],
      onAllySummon: [{ effect: 'buff', target: 'self', atk: 1, hp: 0 }],
    },
    name: 'Herd Instinct', text: 'When cast, your creatures get +1 attack. Creatures you play afterward enter with +1 attack too.',
    flavor: 'One tusk down, and the whole herd charges.' },
  { id: 'bastion_oath', set: 'core', rarity: 'rare', type: 'enchantment', cost: 4,
    triggers: { startOfTurn: [{ effect: 'buff', target: 'allAllies', atk: 0, hp: 1 }] },
    name: 'Bastion Oath', text: 'At the start of your turn, your creatures get +0/+1.',
    flavor: 'Every dawn, the wall grows a little thicker.' },
  { id: 'ember_communion', set: 'core', rarity: 'uncommon', type: 'enchantment', cost: 2,
    triggers: { onKindle: [{ effect: 'emberGain', amount: 1 }] },
    name: 'Ember Communion', text: 'Whenever you kindle, gain 1 Ember this turn.',
    flavor: 'Feed it once. It feeds you back.' },
  { id: 'ashen_vigil', set: 'core', rarity: 'common', type: 'enchantment', cost: 2,
    triggers: { onAllyDeath: [{ effect: 'heal', target: 'ownHearth', amount: 1 }] },
    name: 'Ashen Vigil', text: 'Whenever one of your creatures dies, restore 1 to your Hearth.',
    flavor: 'The bell tolls for the fallen, and the hearth burns on.' },

  // ---- more new blood: keyword gaps + curve fillers ----
  { id: 'warded_acolyte', set: 'core', rarity: 'common', type: 'creature', cost: 2, atk: 1, hp: 3, keywords: ['ward'],
    name: 'Warded Acolyte', text: '', flavor: 'Words that turn blades, if you say them right.' },
  { id: 'sanctum_guardian', set: 'core', rarity: 'rare', type: 'creature', cost: 4, atk: 2, hp: 5, keywords: ['ward', 'guardian'],
    name: 'Sanctum Guardian', text: '', flavor: 'Nothing gets past her. Nothing gets to her either.' },
  { id: 'tuskblade_berserker', set: 'core', rarity: 'uncommon', type: 'creature', cost: 4, atk: 4, hp: 3, keywords: ['frenzy'],
    name: 'Tuskblade Berserker', text: '', flavor: 'Straps two blades to a boar. Regrets nothing.' },
  { id: 'bloodmoon_wolf', set: 'core', rarity: 'common', type: 'creature', cost: 3, atk: 2, hp: 3, keywords: ['lifesteal'],
    name: 'Bloodmoon Wolf', text: '', flavor: 'Hunts under a sky the color of its work.' },
  { id: 'warthog_battering_ram', set: 'core', rarity: 'uncommon', type: 'creature', cost: 5, atk: 5, hp: 5, keywords: ['piercing'],
    name: 'Warthog Battering Ram', text: '', flavor: 'Strapped in iron, pointed at the gate.' },
  { id: 'rootbound_titan', set: 'core', rarity: 'rare', type: 'creature', cost: 6, atk: 6, hp: 8, keywords: ['guardian'], storiedKeyword: 'piercing',
    name: 'Rootbound Titan', text: '', flavor: 'The forest does not forgive trespassers twice.' },
  { id: 'cinder_warden', set: 'core', rarity: 'rare', type: 'creature', cost: 5, atk: 4, hp: 6, keywords: ['guardian'],
    triggers: { onKindle: [{ effect: 'heal', target: 'ownHearth', amount: 1 }] },
    name: 'Cinder Warden', text: 'When you kindle, restore 1 to your Hearth.', flavor: 'She keeps the coals banked and the gate barred.' },
  { id: 'charnel_hound', set: 'core', rarity: 'uncommon', type: 'creature', cost: 4, atk: 3, hp: 3,
    triggers: { onPlay: [{ effect: 'graveBuff', filter: 'creature', atk: 1, hp: 0, cap: 3 }] },
    name: 'Charnel Hound', text: 'When played, gains +1 attack for each creature in your graveyard (up to +3).', flavor: 'It only answers to names no one remembers.' },
  { id: 'grave_caller', set: 'core', rarity: 'uncommon', type: 'creature', cost: 3, atk: 2, hp: 2,
    triggers: { onDeath: [{ effect: 'exhume', amount: 1 }] },
    name: 'Grave Caller', text: 'When this dies, return a random creature from your graveyard to your hand.', flavor: 'Her last word is never goodbye.' },
  { id: 'piercing_barb', set: 'core', rarity: 'uncommon', type: 'relic', cost: 2,
    triggers: { onPlay: [{ effect: 'buff', target: 'chosen', atk: 1, hp: 0 }, { effect: 'grantKeyword', target: 'chosen', keyword: 'piercing' }] }, needsTarget: 'ownUnit',
    name: 'Piercing Barb', text: 'Attach: your creature gets +1 attack and Piercing.', flavor: "Filed to a point that doesn't stop at bone." },
  { id: 'widows_kiss', set: 'core', rarity: 'common', type: 'relic', cost: 1,
    triggers: { onPlay: [{ effect: 'grantKeyword', target: 'chosen', keyword: 'lifesteal' }] }, needsTarget: 'ownUnit',
    name: "Widow's Kiss", text: 'Attach: your creature gains Lifesteal.', flavor: 'She always collects.' },
  { id: 'scout_ahead', set: 'core', rarity: 'common', type: 'spell', cost: 1,
    triggers: { onPlay: [{ effect: 'draw', amount: 1 }] },
    name: 'Scout Ahead', text: 'Draw a card.', flavor: "Better to know what's past the treeline." },
  { id: 'rally_the_line', set: 'core', rarity: 'uncommon', type: 'spell', cost: 3,
    triggers: { onPlay: [{ effect: 'buff', target: 'allAllies', atk: 1, hp: 0 }] },
    name: 'Rally the Line', text: 'Your creatures get +1 attack.', flavor: 'One voice, and the whole line leans forward.' },

  // ---- Vex's Red-Sash: deepening ambush/bandit identity ----
  { id: 'red_sash_picklock', set: 'core', rarity: 'common', type: 'creature', cost: 2, atk: 1, hp: 2, keywords: ['ambush'],
    triggers: { onPlay: [{ effect: 'draw', amount: 1 }] },
    name: 'Red-Sash Picklock', text: 'Ambush. When played, draw a card.', flavor: 'Lighter fingers, lighter purse.' },
  { id: 'masked_raider', set: 'core', rarity: 'uncommon', type: 'creature', cost: 3, atk: 3, hp: 2, keywords: ['ambush'], storiedKeyword: 'lifesteal',
    name: 'Masked Raider', text: 'Ambush.', flavor: 'Never the same face twice.' },
  { id: 'vex', set: 'core', rarity: 'rare', type: 'creature', cost: 5, atk: 4, hp: 3, keywords: ['ambush', 'lifesteal'],
    triggers: { onPlay: [{ effect: 'damage', target: 'randomEnemy', amount: 2 }] },
    name: 'Vex, the Red-Sash', text: 'Ambush, Lifesteal. When played, deal 2 damage to a random enemy.',
    flavor: 'She takes what she wants, then takes the rest.' },
  { id: 'stolen_blade', set: 'core', rarity: 'uncommon', type: 'relic', cost: 2,
    triggers: { onPlay: [{ effect: 'buff', target: 'chosen', atk: 1, hp: 0 }, { effect: 'grantKeyword', target: 'chosen', keyword: 'ambush' }] }, needsTarget: 'ownUnit',
    name: 'Stolen Blade', text: 'Attach: your creature gets +1 attack and Ambush.', flavor: 'Traded hands more times than owners.' },
  { id: 'ambush_horn', set: 'core', rarity: 'uncommon', type: 'reaction', cost: 2,
    reaction: { on: 'enemyAttack', effects: [{ effect: 'summon', token: 'red_sash_cutpurse', count: 1 }] },
    name: 'Ambush Horn', text: 'Reaction: when an enemy creature attacks, summon a Red-Sash Cutpurse.',
    flavor: 'One horn blast, and the road empties of everything but blades.' },
  { id: 'shakedown', set: 'core', rarity: 'common', type: 'spell', cost: 2,
    triggers: { onPlay: [{ effect: 'damage', target: 'chosen', amount: 1 }, { effect: 'draw', amount: 1 }] }, needsTarget: 'enemyUnit',
    name: 'Shakedown', text: 'Deal 1 damage to an enemy creature. Draw a card.', flavor: 'Pay the toll or pay in blood.' },

  // ---- Maren the Shrinekeeper: the enchantment axis had zero duelist owners
  // (herd_instinct/bastion_oath/ember_communion/ashen_vigil, shipped with the
  // enchantment mechanic, sat unclaimed by any roster entry) — same for the
  // Ward keyword (warded_acolyte/sanctum_guardian, also unclaimed). New cards
  // lean into Ward-as-persistent-axis specifically, reusing only existing
  // effect primitives (grantKeyword/buff/heal) — no engine changes needed.
  { id: 'warding_litany', set: 'core', rarity: 'rare', type: 'enchantment', cost: 4,
    triggers: {
      onPlay: [{ effect: 'grantKeyword', target: 'allAllies', keyword: 'ward' }],
      onAllySummon: [{ effect: 'grantKeyword', target: 'self', keyword: 'ward' }],
    },
    name: 'Warding Litany', text: 'When cast, your creatures gain Ward. Creatures you play afterward enter with Ward too.',
    flavor: 'The shrine remembers every promise it was asked to keep.' },
  { id: 'blessed_icon', set: 'core', rarity: 'uncommon', type: 'relic', cost: 2,
    triggers: { onPlay: [{ effect: 'buff', target: 'chosen', atk: 0, hp: 2 }, { effect: 'grantKeyword', target: 'chosen', keyword: 'ward' }] }, needsTarget: 'ownUnit',
    name: 'Blessed Icon', text: 'Attach: your creature gets +0/+2 and Ward.', flavor: 'Carried from the shrine, still warm from the candles.' },
  { id: 'shrines_grace', set: 'core', rarity: 'common', type: 'reaction', cost: 1,
    reaction: { on: 'enemyAttack', effects: [{ effect: 'heal', target: 'ownHearth', amount: 2 }] },
    name: "Shrine's Grace", text: 'Reaction: when an enemy creature attacks, restore 2 to your Hearth.',
    flavor: "A ward doesn't stop the blow. It just outlasts it." },
  { id: 'pilgrims_vow', set: 'core', rarity: 'common', type: 'spell', cost: 2,
    triggers: { onPlay: [{ effect: 'buff', target: 'chosen', atk: 0, hp: 1 }, { effect: 'grantKeyword', target: 'chosen', keyword: 'ward' }] }, needsTarget: 'ownUnit',
    name: "Pilgrim's Vow", text: 'Give a creature +0/+1 and Ward.', flavor: "Say the shrine's words. Mean them." },
  { id: 'shrine_elder', set: 'core', rarity: 'uncommon', type: 'creature', cost: 5, atk: 3, hp: 6, keywords: ['ward'],
    triggers: { onPlay: [{ effect: 'heal', target: 'ownHearth', amount: 3 }] },
    name: 'Shrine Elder', text: 'Ward. When played, restore 3 to your Hearth.',
    flavor: 'She has buried more wards than she can count, and outlived them all.' },
]);

// Starter decks (30 cards) — what a new character begins with,
// and what village-tier duelists play.
export const STARTER_DECKS = {
  boarherd: [
    'young_boar','young_boar','young_boar','wild_boar','wild_boar','wild_boar',
    'tusker','tusker','boar_matron','boar_matron','darkwood_wolf','darkwood_wolf',
    'pack_alpha','militia_recruit','militia_recruit','quartermaster','quartermaster',
    'ember_bolt','ember_bolt','ember_bolt','kindled_fury','kindled_fury',
    'wolf_howl','hearth_meal','hearth_meal','sudden_spark','sudden_spark',
    'village_warden','village_warden','gruk',
  ],
  wardens: [
    'militia_recruit','militia_recruit','militia_recruit','village_warden','village_warden','village_warden',
    'quartermaster','quartermaster','hearth_keeper','hearth_keeper','beacon_mage','beacon_mage',
    'wild_boar','wild_boar','darkwood_wolf','darkwood_wolf','pack_alpha',
    'ember_bolt','ember_bolt','ember_bolt','hearth_meal','hearth_meal','hearth_meal',
    'kindled_fury','kindled_fury','controlled_burn','sudden_spark','sudden_spark',
    'camp_torcher','camp_torcher',
  ],
  redsash: [
    'red_sash_cutpurse','red_sash_cutpurse','red_sash_cutpurse','red_sash_duelist','red_sash_duelist','red_sash_duelist',
    'camp_torcher','camp_torcher','camp_torcher','tusker','tusker','young_boar','young_boar',
    'ember_bolt','ember_bolt','ember_bolt','kindled_fury','kindled_fury','sudden_spark','sudden_spark',
    'wild_boar','wild_boar','darkwood_wolf','darkwood_wolf','quartermaster','quartermaster',
    'controlled_burn','wolf_howl','hearth_meal','pack_alpha',
  ],
};
